file_format: "1"
id: nyuryoku
name: nyuryoku
type: shield
url: https://github.com/kiri836/nyuryoku/
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - nyuryoku_left
  - nyuryoku_right
